In [1]:
pip install --user line__profiler

In [3]:
#Load the line_profiler Extension in Jupyter. This enables the %lprun magic command.
%load_ext line_profiler 

In [7]:
import numpy as np

In [ ]:
N = 250
def Xnumpy():
    X = np.random.randint(0, 100, size=(N, N))

In [89]:
%lprun -f Xnumpy Xnumpy()

Timer unit: 1e-07 s

Total time: 0.0006633 s
File: C:\Users\arezu\AppData\Local\Temp\ipykernel_5860\3989627619.py
Function: Xnumpy at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def Xnumpy():
     2         1       6633.0   6633.0    100.0      X = np.random.randint(0, 100, size=(N, N))

In [91]:
def Ynumpy():
    X = np.random.randint(0, 100, size=(N, N+1))

In [93]:
%lprun -f Ynumpy Ynumpy()

Timer unit: 1e-07 s

Total time: 0.0006689 s
File: C:\Users\arezu\AppData\Local\Temp\ipykernel_5860\1518057439.py
Function: Ynumpy at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def Ynumpy():
     2         1       6689.0   6689.0    100.0      X = np.random.randint(0, 100, size=(N, N+1))

In [139]:
def my_matmult():
    return np.linalg.matmul(X, Y)
print(my_matmult())

[[647001 585626 564889 ... 612237 612007 642970]
 [701692 656536 632882 ... 666722 654643 684830]
 [643753 591776 578280 ... 652127 632516 659362]
 ...
 [625013 577384 604947 ... 597747 598131 630452]
 [665919 625548 592539 ... 625955 633376 673617]
 [679993 657907 617945 ... 639313 635599 659554]]


In [135]:
%lprun -f my_matmult my_matmult()

Timer unit: 1e-07 s

Total time: 0.01524 s
File: C:\Users\arezu\AppData\Local\Temp\ipykernel_5860\3337150348.py
Function: my_matmult at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def my_matmult():
     2         1     152400.0 152400.0    100.0      return np.linalg.matmul(X, Y)